# Generated by Django 2.2.12 on 2021-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/%Y/%m/%d', verbose_name='Foto de la persona'),
        ),
    ]
