# Generated by Django 3.2.9 on 2021-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptp', '0002_persona_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='club',
            new_name='signo',
        ),
        migrations.AddField(
            model_name='persona',
            name='dni',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
